#!/usr/bin/env python3

#  INTEL CONFIDENTIAL
#
#  Copyright (c) 2021 Intel Corporation
#  All Rights Reserved.
#
#  This software and the related documents are Intel copyrighted materials,
#  and your use of them is governed by the express license under which they
#  were provided to you ("License"). Unless the License provides otherwise,
#  you may not use, modify, copy, publish, distribute, disclose or transmit this
#  software or the related documents without Intel's prior written permission.
#
#  This software and the related documents are provided as is, with no express or
#  implied warranties, other than those that are expressly stated in the License.

from sys import version_info

if not version_info.major == 3 and version_info.minor < 9:
    print("Error: Please install Python 3.5 or later to run p4studio")

from self_check import check_p4studio_dependencies

if __name__ == "__main__":
    check_p4studio_dependencies()
    from main import p4studio_main
    p4studio_main()
